name = "circleci-scheduler"
main = "worker.js"
compatibility_date = "2024-01-15"

[triggers]
#crons = ["0 2 * * *"]  # UTC 2:00 = (Beijing) UTC+8 10:00
crons = ["2 16 * * *"]  # UTC 16:01 = 北京时间 00:01

[observability.logs]
enabled = true
